In [23]:
import pandas as pd
df=pd.read_csv("test1.csv", header=1)
df

           Period        Short_Desc         Temp
0           Today      Mostly Sunny  High: 40 °F
1         Tonight  IncreasingClouds   Low: 32 °F
2       Wednesday     Mostly Cloudy  High: 44 °F
3  WednesdayNight     Mostly Cloudy   Low: 34 °F
4        Thursday      Mostly Sunny  High: 42 °F
5   ThursdayNight     Partly Cloudy   Low: 32 °F
6          Friday      Partly Sunny  High: 43 °F
7     FridayNight     Partly Cloudy   Low: 30 °F
8        Saturday             Sunny  High: 37 °F

In [18]:
df=pd.read_csv("test1.csv",skiprows=1)
df

           Period        Short_Desc         Temp
0           Today      Mostly Sunny  High: 40 °F
1         Tonight  IncreasingClouds   Low: 32 °F
2       Wednesday     Mostly Cloudy  High: 44 °F
3  WednesdayNight     Mostly Cloudy   Low: 34 °F
4        Thursday      Mostly Sunny  High: 42 °F
5   ThursdayNight     Partly Cloudy   Low: 32 °F
6          Friday      Partly Sunny  High: 43 °F
7     FridayNight     Partly Cloudy   Low: 30 °F
8        Saturday             Sunny  High: 37 °F

In [19]:
df=pd.read_csv("test1.csv",header=None)
df

                 0                 1            2
0          jupyter               NaN          NaN
1           Period        Short_Desc         Temp
2            Today      Mostly Sunny  High: 40 °F
3          Tonight  IncreasingClouds   Low: 32 °F
4        Wednesday     Mostly Cloudy  High: 44 °F
5   WednesdayNight     Mostly Cloudy   Low: 34 °F
6         Thursday      Mostly Sunny  High: 42 °F
7    ThursdayNight     Partly Cloudy   Low: 32 °F
8           Friday      Partly Sunny  High: 43 °F
9      FridayNight     Partly Cloudy   Low: 30 °F
10        Saturday             Sunny  High: 37 °F

In [21]:
df=pd.read_csv("test1.csv",header=None,names=['period','short_desc','Temp'],skiprows=2)
df

           period        short_desc         Temp
0           Today      Mostly Sunny  High: 40 °F
1         Tonight  IncreasingClouds   Low: 32 °F
2       Wednesday     Mostly Cloudy  High: 44 °F
3  WednesdayNight     Mostly Cloudy   Low: 34 °F
4        Thursday      Mostly Sunny  High: 42 °F
5   ThursdayNight     Partly Cloudy   Low: 32 °F
6          Friday      Partly Sunny  High: 43 °F
7     FridayNight     Partly Cloudy   Low: 30 °F
8        Saturday             Sunny  High: 37 °F

In [25]:
df=pd.read_csv("test1.csv",nrows=2)
df

    Period        Short_Desc         Temp
0    Today      Mostly Sunny  High: 40 °F
1  Tonight  IncreasingClouds   Low: 32 °F

In [27]:
df=pd.read_csv("test2.csv",na_values=["not availabel","n.a."])
df

           Period        Short_Desc         Temp
0           Today      Mostly Sunny  High: 40 °F
1         Tonight  IncreasingClouds   Low: 32 °F
2       Wednesday     Mostly Cloudy  High: 44 °F
3  WednesdayNight     Mostly Cloudy   Low: 34 °F
4        Thursday      Mostly Sunny  High: 42 °F
5   ThursdayNight     Partly Cloudy   Low: 32 °F
6          Friday      Partly Sunny  High: 43 °F
7     FridayNight               NaN          NaN
8        Saturday             Sunny  High: 37 °F

In [29]:
df.to_csv('new.csv',index=False)

In [30]:
df.columns

Index(['Period', 'Short_Desc', 'Temp'], dtype='object')

In [32]:
df.to_csv('new.csv',columns=['Period','Short_Desc'],index=None)